apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: todo
  app.kubernetes.io/component: web

images:
  - name: ghcr.io/mayne0213/todo
    newTag: latest

