apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-todo-secrets.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: main-sha-56426b12506d79c9aea20c4ccedb56318c0a8478

patchesStrategicMerge:
  - deployment-patch.yaml