apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: latest

patchesStrategicMerge:
  - deployment-patch.yaml

