apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

resources:
  - ../../base
  - resourcequota.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: main-sha-62157e0d1d7aef81d49a6df5dd5f8b3e3602c208

patchesStrategicMerge:
  - deployment-patch.yaml

