apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-todo-secrets.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: main-sha-41a1641c41cca6f8f0409c1845b6c294b46fc11a

patchesStrategicMerge:
  - deployment-patch.yaml