apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo

resources:
  - ../../base
  - resourcequota.yaml
  - sealed-todo-secrets.yaml

commonLabels:
  environment: production

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: main-sha-79deced3754eb0c7635c8506065aefd55be7d001

patchesStrategicMerge:
  - deployment-patch.yaml