apiVersion: v1
kind: ResourceQuota
metadata:
  name: todo-quota
  namespace: todo
spec:
  hard:
    requests.memory: "250Mi"
    requests.cpu: "100m"
    limits.memory: "500Mi"
    limits.cpu: "200m"
    pods: "9"

