apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    DATABASE_URL: AgBk51tTmBuI+6L0NhPliovCLpt18kXq1tCjnRDS5mY6Xfoliyrjqkq7UxzKCv8J9FfTTNqawdjVBt3cixVjFnj2wQYQW9ELr1QK4h4xtdci3/jJCvwS00pn2qjO2Huo7SWgtDY7p5O9OaOf3eMe2pBKVLBeFKbMrTWt8XH8Ig2GB3HdgE8AcKni1chSJy20VZ75/Gs/KhvRGIoXv22zgqlJV2DPnbDk17pBcOKyHpGJzf68K1c5nJyankOxffCBvyua3c+YVYLxSAiKO4epgUd6BvgpDyl6IuExRhRcVpqnBRnbWjT6YlZN2XBDH8e3b7HrDby9GS7/cJuCbuCQU99A5fVZLNoDgTFVU6bnyaKeKXEQxZvRSJR+7lwRiyCM+8MsmD2S84Tye04MIKrPJRV27uaXmEYEQ7siDfHNL5C9AhcsrfX2dkpBdUnxwkfMPgg71nYlbo2neeUdPWJtZfhjaLfEx5l4gW1mG+p3QlKEvEiQ438i3kUElDZBpr8nIPMl/NkAGrJ0VsuYW4TTj5ExJsXX2NCXowlRjh6UM/S3N5m0WgAukPsbHfCPq3lC8Rcw20bD9I/4m6DUo9HYQ3aEyHwuwMWp3X2Tsx7OgFXeH0NDjoABXpypzRGC2YDx1pbNjdweeJcrbGLbqhnELSE8OHm0uRhS4pry7nYPDufrREkr35ACP1tmX+pYQGAZDueRcsSr/Gyouboxbcd+u6z2Tjy+CqfGV6FrxUMJyMqngWKOGl92Nn5kD5c305FfSMmbIY0sxnEt1MzbQFY+ogROmO84jcbLkL8gzUfyNCV610T5Vn+u+CzjElQ=
  template:
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: todo
