---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    database-url: AgBg7nC3lqjal0EqXw1wjAl63CO9dmXwaKG1QT63WtpavuZv+0DFI4+CXWR1ECpV4TaSyFR5AFX+UwlYuOXOITxj/TceS4ToiUY6FIER2dVIeprT2NMtpHpEvkGYDXGjmIdGEfkKajwxo3GQjJZmYJlORJxagYQELQ24cYyvogjFGzXgQyhGlAZmHrbKjsMlImsCHtxijPYraFcawGL/wcm102v7GRHf0vGft9keam9ofaiUdydQ0fb8XJZctfrjdLVcHN54/5fBKgyOiAmvas3RDZDIjwWnmwaqjo5U3uLGlbCHBgTLIkB3pG4Tsrp93B4Rexb9hqesMcvzmm7wzZ23gz4yrC44xMUfMOpZkXNSYJ9ZDvkzj2WYlSYPhyfqfVSd/7sz8kraCVVqO4oQzDIY0aPfZhcVhbu3ZE9OrbjSTzATfCZ27fn3sRtoFeoBJ7luStdfAJnd0Wa6CFo/VyMwQiwFeS/+83RvxrbpcjmbpxBPQYCfoCTk2fITc6iAgEXmtT9naafqa/z9NaZ8PvEcl7rf9xVQILEqTg9GzTDnPidAif7ILm+g3IjfhiU0Ifp6AbIRp99iEn4PYls6G8AEjuwBqP0NSot2IxI14DLEleO+gVxzzD/4PIbwPlEIFoQXdLLD6QoU8CIVYbA1sTzgbmkuibkFMCBT/ZcmiqJaGrKDS7/EyXxPbX8xWZrxqbIjsEQ+jcwebgeOZrX2cWxU5LBvgJUeiP9Uf7yR/d7edmCyXXKPDWjMU3waOxsOKvuTLwOW5c0CwVjUi1d2eLhPmRJCmefOE3+O1W7jHKziM1oeQxywAlo244eif+N8rYg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: todo-secrets
      namespace: todo
