---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
<<<<<<< HEAD
    database-url: AgAp1/AUmSpG12Td9HxJ+UkLyAHCz93JMNGj+DRha1uSjZHJzLGJnv4KoGnefQPBpZ/TekAyDEtnGbegX15xmMwLr28DhNPsOCfQKKInIjAszDGCRQvZTEL72P6L+hdsTvbLISGy0nzo/xOOTfenWIF36XsmDU9FZD4yIldUfN9pzJFEsJ7NuC25lCdZCvhMiTbJH05aD2LwO7tf1Hg8EfeB7SFZE1HFQYScUwqUDLWQotUxOqZ5mck021X3dx+nQq1pHaBm6yvlpuPHFOGBhrDFemaNScF6PeqWxz29PHMASmzf8He9LDHEZRrSnYjmsdoqkc37omrARfV62rs/mlBvQEfFoTmD8B8Ii1/tPAFNeL3K8/6LtRn27jmL9Z9+fY1gNna/fPSvE8HnUjdyIFhS1XkvigXFvAHAyxXv5TItsU5TYEZJKPAsuaJe30Umm3Sz2Cr3h139Dws5pH4lBggxFM9eJzF8McOazCBJNjjFC71MnZLJmSxp6Ttgb+FHaDdiqlfOhVU321QdBh6IkCbRAf9aUzpE83hPJHWJ/aYzdU7VHjA3wtbN4JD9YWkhmnCuByyQ8knwjPAn01l9rfVUVB/k+xBpK/L3rWk2NaQHpIFDRMQ3BymHWMw92GMBtr1o/FqYfGc8pDFwMyjgrhfFDNEeaLfjg7qd+S6JclHW6d4F2ldizkYjqzq63GuteJdM0+fl3CzyxlAIdAXleeIgdSWhXMvX3xvbF7/iN7agq/sjNDIdiyAbjmcV4U2z4UtKOzDiMozTPYhOBX30WLDfSs3wqF7n4aTY6WmYPC8ra+3TV/4EzEkbPX6KKlncS+k=
=======
    database-url: AgCb9Tr6QALpNU5ZHGNxDd/iWUIuCLhbRNESk7aPrI2NzpTuUULo+KkCbl5mCLZ8kK1nttTNZnQTJ4DndnUWckOrOD7+2NRBsWOWwm20Z0Y0dM0iQyHK++xeHEDGZSjzUXUmkJMp3B5knjltDINEnlFgnDJZWhOWZjZ/5RrG7gJEjcq/v0wMPe71lk2WdXBnJ6ck7zpI1gl9b0oFzMA2wdx8McjK3KhBuoLEX/G+4RKITiY68EUW/PyOGOctNxT9ZxuKBTlWcsHVQ1KSxI+nrSV6GNA5F7UcGPdWs8x+QV0ntAzqtPZGyenIwsS9DPUFJhAe3g29kz70BSfWrOPq2q/e5Rda+XSEvnAwHsvax0r3b0pKCnLMQpz6Iclt1l2EEmjU0Llys1gkhYJqN2mRcQIWSErT8kKBvNzmY+eG9K0AzSb1RfC+8H5oXHrQ9gPih9LHLoaUIgAPHXn20kAKfPhwEuW7h394ZponDCHljx5lLB1QPDUS+V5wbgN7y+rAPhPgXTw+Qs4lXMi8hrrE8EzEhi2JFys/zSHsXsWKVCKi//ZLVK1FxzyniQpb2Fwqy7Odhk68TAtCqoiRGzI/faaZeTMdjFggrD+BNqaIVEVNoJ41gRECsdz7Egskc7+kyVfvNWx6IP3O0zr8Uxh7wMr+bmsEUdO9RNS1AgaCK/o4k0t49xmjJ3wpIt/MtGWlnY8x1pUq+MV01o8ZW2UKojTHhMegi3LTdqsMYivAG6V0+4wzMPFSwv9rB7ObDLU7f6RRlMQU73hrsRchOmnl5UiNh2RjSKm+yNbqOhZI
>>>>>>> develop
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: todo-secrets
      namespace: todo
