apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secret
  namespace: todo
spec:
  encryptedData:
    DATABASE_URL: AgAhLruziQqTOZs+OKWJoo1GxXX14nYJ+f/RVGX+2znTfB2QF2uscgu7f6nk5t7o/X5h9ziDkmkypJp3tbMg2ZT+NWO1Om0AmsSZ3Y2cZLZknJczBoO9smp0477nMEj7gcp6uvOa5C7hdhYVa7ixdV40UM2i0EWjeQH6T6eJtKwZ8HrtCtAnMcwuURh/wJi8TUjH75tOLBJXpu0kZ753xa75g8fytJnmIg2v8dzNFif5NatfM2h8E1tvmhcVqRFGjX20T7L+gsGcheOmW4juJ5Q8Qoxg7Qf55gHCE8nOgBJed+Da7n2AaxjDa1EvK2dAlELYezzGZyzeX0g/eNrfuf8nIeV90JYpy+XAO4D/FQgWV/kWoJDcYNt3WnkM4aHLd575W++mmoo0M5lu29+ne0+aNHb5pfNzLfecTUoVH0hpedfNNQ4ox/8rgPk4lxs3XuuHTdHPnuKQYST2yXE/KsH2x57WKI1dck5LkKZXOZv15LlMTda934u8VSbyzDWuGujijknFTsoJfEb8m4Tb9Mq8HVIHqMdz40KLYcMIlBisM+5hrSKyMLQglEJ/VMRerDdjJYH/PxnaivtHUZhZWCQox216Tmg6JJegH/bNj2gZORmtmTvKYk3g+GqWg4eIinvYKl1biwJlQUyo/LAXG7IEOtjHq0e5/dgIqE6/T5ZSSYxdl8HlrzNuoxIJxgPh2XxwYe8kE7o/05thB2RGruyzXsziI9poLESEsujgrA+SRzLwWNUaO9fOoQP4Rp/Cv6iCl3s2XARxYg3csaxz2p+DGrCUltY2uKQ0ZQToL7mva/Xugo82JxS7yqA=
  template:
    metadata:
      creationTimestamp: null
      name: todo-secret
      namespace: todo
---
