---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    database-url: AgApODB5QX8XgHgrCMp318Rpy4Srt/7yJaUIl8Rb+kj8SQ4sLEJKLHOgI9FYg/U2lLS3V2/sZq5PFP2keePm2kuVTK2orj4833RHGBoFIjv12E+3XBVfuEOXBdNFD7PPNqvhEwOYDSRz1JeVDFtGBZUUL21/+jA6rF86fvXNolt1okgpiOd2g3QXTRuP49EQkEG99n2WfjVn2B+Wm7n7P8EvdP/3EN9T8r8/VOjio/TE64MKLI9Eu1rZq4/x42QgTl+sN4uI9nrHeSwqaM+cVohEc0bfA/JNmbf8gkDvUwiZROGZNVFylWQy1uRg3Xm4NKuH1LjlAwqr44RAXSwqH/d0IL7Il/bgmPinqk66r425QXxC+ha3NUZvWaemaT8ZhxrmPYxzAFLZNp0Zc6530LYFAE+2FmKL7BbIj59PBffY2GaqKHu+Ymq/jSziEVYHueVilLUSL8y616OQDEEn8s0ysxh/FCqm/cWtwiLzFsHtjYxdDIfJRBKSiMx+HWnvv+15U1MvUNr9jIZMD1TEeNVWtQLP06uyeiWOH4S0K0kD4mMwOKluQ1vFk74AGFHff+tcf/xdX+V/ZEMNWdCSmnKwKuRt38oBKNojbVYsKaT1axI4MU5O6nxrDe+qu4qp/M8To8HDL5G2/mPE/iAc4W//DCA0qN+jJ4DyeNWRO/T6kBG89AtAF56ffADBRHffxh98yCepqY3zsStNnVYLYhEJdI9LAyVJfo7jf15T0SvVBZup+H+w28bRQ4hyeXWLQNkYMr/oTcN45yFEm5oRc6LZQj12cLIkTXnQZe6ylzlj+R00XLacG1Wr4SEuM50=
  template:
    metadata:
      name: todo-secrets
      namespace: todo
