---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    DATABASE_URL: AgA4/EMOaCVhYjZKBxw6H06M5Yv+/6Rkrh0+SIJhCdHpOphAEoGMO7IlCsndKRg2ALqLsjrW6R4Wi8cYUNuwzDSoZi823L2es+Fou2oKXLg0dVHlyOCTFeRxZ/4U7MMuWInIjuaKSUrPVNfFMiRVCvkQtmw7gDORxNc9q8bbismVVjhPVM5YVWBnV05Tg9TkdGoFlYjr/mnyPH8S+vZqp+ksuMgCkl3nm2tR/Y30JZPdYPDNWtCVhl4EP4U0apiiZ3QAKjWuoFaqnkU3reaZVu+3XL/eZ7zOtyITPYHjnVVuKDXPQ8j6jFw2f8fqu4D3IvWzQva4XYrGXXUtuH0eEqbIIuTW9Shs9Y8g+qQ7lETdjtTT2F7lvTWIUFlmDfM2f9baMl5vgdZeiwnDU6xEigtMqfSsWpJaAT/HRTZOcmyZ0eQOu5+KHLHNpW4EaQpoDpFZ+hvmR+eeuU/56MChrXMdF+yrPZWgVeE1Uog9ZZbAn/2h/HhjzzUKV8CW4H8+otxI1G+i/qsPbN5IL9q1oG/EhP3lPFiUUEZcpUEQyyhdh+dCpihu+kpNYi69Z3A9z8I3aiiEyJ/8ycsdWSBu02br/ll7sT1OvCIP7ux2CJv5bllKyUAqpvKD5+F6Bd+uBmrTWI/HaXU4yuHgbbVq/+ChyQx0gp7fUD79rVY3wm01Y5aX5frVUrBfeZxhsirSlez4AKy9cnxl26GXqGOZR0FQtu8Q+t5/UUMlBRZJpcSXvBu4CioXjwmpp46r9fC4Ai0oUmeFBgefTcIzNYeJ/shuYHSYXY3WEtHtvdT2oUAfEVwnnFaVBtOgoPuDx1U=
  template:
    metadata:
      name: todo-secrets
      namespace: todo
