apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo
type: Opaque
stringData:
  database-url: "mysql://root:root-password-change-me@proxysql.mariadb.svc.cluster.local:6033/TodoDB"
