---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    database-url: AgAhBMJ/kI8EnlASO4N78+O3d4P8bW81RkqdI0ftSYjmafI9VFugDxWf9bS8LcAmPfRKGgMmHqsPfLogfB2qDnEqL/2194stFsA8fY/FdnV6PE4tF8aaPsO/byeTUs6xdZKSzDvU/xiEyW1r9OVTkkNs4OKlzFGhgjznD8qfif7xuCK68QImmEZePiZF+xZ8YCt0T1KjnJZ6ExyA/zJxjZiexWMP2Ay6xKtiqZ+z8zUO4VgTTRkGUo/wvPGkWAk1Gm+IMbUjell0B/6VCDYPuVpvutRvhnW5bE09ydBGa8FlxMPZxp8YR3GPbuZJdvkCAZoAXAt9Sqi7jxd3ed+ET/IWjdfv/X1QbCqL9V8VAca2XZyzEORj+8yFaXbnDulkcda/S1JQrZXgHR2bZlFDRjuyUmocAWityoZvj5KgLRjQ1slV4ufADVRpUCJ5pMN0Prfht2YUwIMfmAzRyV00rBFzKjZEAp0fdFY5wn9Xb3FQbeyhFZeqMAQkkL0O9MEVZIKku3ArV78p6uLQeydzii7NEXd2FpaPcbIExUE5/HgyGkI2KHMbQp1a1zb8V6g5Rt69l0U3EGM2jdYhjmzyvijWxAvNUSmrYB46jTAaFch0n5wujjveohctTHCAi2g89HKUWyISdEMnhk2IYmiLx6Ble8/mlVRx2xj211UB75og7ISzXPQ5ZzRKsnR5+NGaAMKGh5Z3rWmYeLsT7jwrCSrW5JoF2YeP+ijtAXo9IO5BXmjOerduD3WVZj8j9+ZFv7xE/JoltUe5OQCjbVyZidEpKiaP2agvhjTdS0+N
  template:
    metadata:
      name: todo-secrets
      namespace: todo
    type: Opaque
