apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    database-url: AgCbdLajT2+j/fUuJUa6c+tkXC5RVWfW2GUudGY3z9iTVNY+zeTOEefIhuooqxlVxMwDvvaq/3PFQXhcQJJmte57HYP7thhTWGNSkkUDrLaFVjju0R6vLWEGHITH128r+vJ/JNVKFqD8p3siCAKL5VDLCno8Kvw4kkZiBtIYWD73R3xgW2PRXkEg/pWED1Bso7dWzLQ2NkoYzAtCgICjnK6fD7EhOg81Db3Ai0a8mZMVyWT0DVTgDg0WO3MwbK/nLRMTEWeaVzzfegffx7RY0YcONaznebkLYhI+nKbMDzG7284rBADu3+nM7lqy2PPC7xbBcnKFgKXSeQxsP6OvtVSBKHhc7DWz/bABUSX5NgZzCJ3HhtHv+C72ys7pi6PaD0bQOiagjTTO5XpirjjLi2m5jd8gGcWibjgwlislpJqdEqGB6eepzgbEyKYNQfEQXp7RrX85IugGhv+v8yUUlPzqgsgHyylUlNZROHsznz+7T59ypRXvY9d8XwyijpjneRoR5h84EbbTkBwYkZLde2XHbLuX7rnhPw7aMt1+9V7f1cZqtN1CFvsEEGOoW9MZH5k5BDlppP2IGrVHNNGX8eK/nD7XEHN9Oxy7FKbFGETRogTHU2PacWYRvN2oUFFIxJAZN2NCkmfSaHzvr1MeGheCutVCF9yygFTBIj9ayjmikgs5QlPlY56X47k2ZItf8jIQHZnzUEaEQ/5SgOa2jRGKaNaylGvViBprwK6AKyesC/9SsQHVnrheVUpESD18uQ9ke1KomHBj3sKrIpid5bzxiXzYCUk9FsrXIol+DwPjVr7vOkIji/yxETY=
  template:
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: todo
