---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: todo-secrets
  namespace: todo
spec:
  encryptedData:
    database-url: AgAp1/AUmSpG12Td9HxJ+UkLyAHCz93JMNGj+DRha1uSjZHJzLGJnv4KoGnefQPBpZ/TekAyDEtnGbegX15xmMwLr28DhNPsOCfQKKInIjAszDGCRQvZTEL72P6L+hdsTvbLISGy0nzo/xOOTfenWIF36XsmDU9FZD4yIldUfN9pzJFEsJ7NuC25lCdZCvhMiTbJH05aD2LwO7tf1Hg8EfeB7SFZE1HFQYScUwqUDLWQotUxOqZ5mck021X3dx+nQq1pHaBm6yvlpuPHFOGBhrDFemaNScF6PeqWxz29PHMASmzf8He9LDHEZRrSnYjmsdoqkc37omrARfV62rs/mlBvQEfFoTmD8B8Ii1/tPAFNeL3K8/6LtRn27jmL9Z9+fY1gNna/fPSvE8HnUjdyIFhS1XkvigXFvAHAyxXv5TItsU5TYEZJKPAsuaJe30Umm3Sz2Cr3h139Dws5pH4lBggxFM9eJzF8McOazCBJNjjFC71MnZLJmSxp6Ttgb+FHaDdiqlfOhVU321QdBh6IkCbRAf9aUzpE83hPJHWJ/aYzdU7VHjA3wtbN4JD9YWkhmnCuByyQ8knwjPAn01l9rfVUVB/k+xBpK/L3rWk2NaQHpIFDRMQ3BymHWMw92GMBtr1o/FqYfGc8pDFwMyjgrhfFDNEeaLfjg7qd+S6JclHW6d4F2ldizkYjqzq63GuteJdM0+fl3CzyxlAIdAXleeIgdSWhXMvX3xvbF7/iN7agq/sjNDIdiyAbjmcV4U2z4UtKOzDiMozTPYhOBX30WLDfSs3wqF7n4aTY6WmYPC8ra+3TV/4EzEkbPX6KKlncS+k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: todo-secrets
      namespace: todo
