apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정 (dev 브랜치 사용 시)
images:
  - name: ghcr.io/mayne0213/todo
    newTag: main-sha-69b3fc9deb45c82ac19120458829d940f1f7a498

patchesStrategicMerge:
  - deployment-patch.yaml
