apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: develop-sha-5933c29ebf593bd3a23d8ed6cda365ebde05ec14

patchesStrategicMerge:
  - deployment-patch.yaml
