apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - sealed-todo-secrets.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: develop-sha-7978458382ab33d05284d3248c4fe900dddceab4

patchesStrategicMerge:
  - deployment-patch.yaml
