apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - sealed-todo-secrets.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: develop-sha-0f0ecc38c9617e5343c28c0f91b0ff4c5efc8b9b

patchesStrategicMerge:
  - deployment-patch.yaml
