apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml
  - sealed-todo-secrets.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/todo
    newTag: develop-sha-489b5be29a98d8ca1fc8b92aba3f0981806cdc8c

patchesStrategicMerge:
  - deployment-patch.yaml
