apiVersion: v1
kind: ResourceQuota
metadata:
  name: todo-dev-quota
  namespace: todo-dev
spec:
  hard:
    requests.memory: "150Mi"
    requests.cpu: "60m"
    limits.memory: "300Mi"
    limits.cpu: "100m"
    pods: "6"
