---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    database-url: AgAta/n37McSBa3PXKSAW0evIj2a/jJqzoAZITXOL+MA/6KPDpzTmfsvuOTmUpMbrJ7qrARafvFHNfI0Gjj+5/mn/yn0T9t5a6+a8CIAZasMcMdfnJ8cMz6GzIpIqU5xhQbOrW9fcHfKlKWRGGf6iA3rBK1wzuVQlPiN4/5jqktx2XZKAXtqppQ88lY3htDGO/tq/B9ak0BaJcRIEQPGCZ0hkfR9/Mewl7fDL5reeTUDaoikRQAdZVOpuqtovpe3MAdz5OW0acTMdkcYOr3fee8JsI+nk5+yVMXVdyx6AkgH9hUwSolnHj8phOMBVJDLMY8iDpczeRiXNXWZwFjZEnvhqEabp5wqPsKspX6fXdYEeMaMyWlIrrdvEl++tUYpuyYlAzx4f/kpk2Qvr7EOiza+OQhJhYtPOP3jHa99E8RITHYReeDR6EuIvjx5vaAkCBFkyySMn0ISUv7WiNk59rRuZzvpBsx+i3DNj7Rpr3CKK6U5Fv5UJsZM3MypAb2vkEjp8crX0xg+VhnER1GHcUoYNtWo+T9ZurD8S5b3Ck1QM1CKkupJVSK/cSHqgGEKy3mfOFwQkzXkzc85FnItDcPq5KiOY9avX2re7QoAwu8BVkGE4mq6gdkjjReJ01jfSmY3HBMwAPry/1+d0a7do85UpD0RYrmk/2PLZBa9wpaBfGrRGxnFpFHK+utNf13Av12gQvbznCp1VbAhKPni+f/SqbzBXxSewkDOLRSiyaVoBW0lj0T1nvBx9xhokyRJo3i1dHc09thlm8r8mIqid2NGohRRIpOnKiqIs9yZpeuqRsWwzVb/dbftxEIui0g=
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
