---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    database-url: AgAE0D9MirupfI6Z47tGjIp5RkdAFh3ucTyEWWRG7qbgotIc3r910phSVLQi52hs+odKz1G8cIBoxGFbqt+rIlBDqkQ2OSSONC1LbZT7VM9Cw69pJ5IeTu5Vp2+YaO7rCLIvijUL+P4YuTU5jnbhU3Upds/qnslkGtokwFLslHGX/cr/4MOjBW1IU70l4wui/LY5MnJCEu0r+J8Yuhsir78+BWMR0lqnXgXSh9naHTRNHG8OmcutpU6idgawD5szJb27Qjkoygsxpma+XtAHI9Feb+tOcSplUxQlANWdYz4T2B0Wzq6krMEH8Ypl4iPmf1z8CgRbkswdfCUEAXy4z4UcTBNeLO34zzYHys4y7eXTcMsHTD3f57b5HBZplgo0wya1UfSKUuQHFB2sWBptNXVNddxwW2BbTRYhKr9etXIXO/QrLoIVF/u8vtDjevQM5xjKIk28B7r80X0ZJsMK72KQM061Bk5GZMMU9HA3OaVwgZw0Alx8+ofTuC1FYFn61oQvDmviSiBm1o71zIKG+fygHN788MkY5L12Q+ZVky6Ol6lW6mh/TfDdIbZwcFum4Rn9RvApjpdiO/5OKnzGm+yjg422FTlY/ujFolrIClF7jGhsdfqCR++ImqO8g44N699fjSVUf7f8GZc3FreO8Gu05MFwVS3mqwMMYh+ncc8leuZ/92GQ4F9KYpMg/0MDUhZALR84jSHw7QUdBT6grTI6LqsVyse8ShFRhaAtpteT6Bzny5de4C2PA/HSg0atCOAnc8wa0SyD2qoJn21orB3lHMmpZ9D5L8HtVJhDPiIh4kuYkgLBtKGTvOMZZ/gHrN4=
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
