apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    DATABASE_URL: AgCdr5Ssc6Brq9clxvU1RjHDdMI8yMUES0einvO0gJtww21eTl1nu9eh/pom7sQhhsoAUUUcV/Qt/HT/qg8DzNR4TMCXqG+6xSMH1cIjEDMSjgWMlh6or0AsM95EdV1gDYn8MVbGD83hq972hCv6ad5UAln8LUOKaph9aYE/SwmlWoRSZMoyO1EKIdLXvkLsjTdSZIz8HvGvHmou56eo8o0UvJCMAOs4bSPPXKl1l+mUoy/VOgE6UTtgbdvoN/1c89Y+6QtDZYSNrkLPnlFIWlxNL52TQoV4o+8IujRy5UZ0+gNy9h10SyEAmW4YznkArvAgCDrRscbVeAPPpJ/2tStg6EBciYa6IDnnR1Lnm9kbW4ffhcBY7AiV3urEZaYSOB8f2e3x20s9iviVqyzJD18+FfbqzMUnk0v5L5qQIyzmBrjDkQRXVL7/yWUFityosnDNpQwTuCFXI2Fs3IoXCPA3OCicRwhsQkPiWmcBiG5G+/P23buURprk0t8liypdjNPUdpgXttdt+in8NhKBH237geWDbcuK0BjOI5Nus3Cq5EeGuKe0fvH+TY/jhPV3Ws2VjSlyubQC88a4g2YxNdjUA7y2e6fo7by2ZVB55cPndocQQuAPJ9eLlcA3FuNsIq0MUM1tkAj1CFpe1yFQaSwaUfWaKr99G5x4IMQ9K0FDTdZU4J/YJcO8L6XXfh4J81A4VxBHxbS+WMU8Phl89bzqwItEP+20pInc5OMa14fXsg/aOQiresgXxAL/nimzRtEo9hDv1Dj/ylo8a6bqPZdsovUNp8k9yjaCrpQqwT7N6bVAcFg=
  template:
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: todo-dev
