---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    DATABASE_URL: AgBJpBMqt7MzkNhl6RB+GN8ZL0sWjgbIh0UlUHo0NmH76YeqU6Frf+y7HTXi1A3n6c6nnIK0dN32ehmNUsNFCHxAPJ6BcMuaAJwujRkXZeBNrna1C1UDswn4m1Awytd6IcKUqa/vREXEds+7R/LOue/VQozyj5S+ceNBI0bJN/bhJszFnF4GJNP+A6/PXQTKbk/Q1jWkBNjv8t//uzPl5/mPRXuQuAKyL0qkNibaE8kXBabpL7AMQUHY3tZC/3n5qdi+6JHnPuYjRSs/Hk9cd3axsFONrG7hLoprPXjCxGJW6Qlt5NN+48l2zQ9LkOSwK9VRhXsXpraoC6kzi81L+SIJcYW7+tY0ip9mNnJh5DAk16RT85QO22F10wKxXR1agUJ5cVWJiGheyFFM2Ald42I6E+FCL6f2KS8/L2SCoAQqwK4HHnxumnHQwG7NhA0cZRKBQp5MriFKijuVWF/UCZOBOBoKQGA5zvBY6skfEN0MMGWT4yXMhmnoRQib8f4kkT3xx+PynYpjRxSGXcc9WAGead1VXl1rftELds7ZwBmbiYlwsoCuyoiVXa4+9U8RYZivBpDToNXzF5BgRTbG8WhQBE/PSRbqtW4Kcmn2naxf4e7gF02T1AZNyxj1H68q7XUThhHjUQoLQexy3kJL5X+6gHkZ8PzATAhC2M7+YunF17i2ObhkqO77MXm3/uRunI/i4Cormw9cz2Npm060Ayi0Ph+ssjqcpXJMTsuWvJxRdP9QU7AGPw1VxS8XM5jJteSprxkVZm+167tnymbua2VbZQrb5V6i1VIPzq9JNKKx6LiOUNOXSDLmHgW4NzM=
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
