---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    database-url: AgAxZEuCQTwkEcWviQsqN0YtQNb0UaPhgEeSqXJLZddyERnxTB0rUODM7HJV5HB8vw/vSA8WER9GPdzf1g8HnEzNyUvytojaukiPPngFENRaCx36JBFi2u5291XgrO6X8QdLv9ng//RPI1/ZrLlKvDJQRqzJpm1M6dyiu/OKN7TgXWmFml9thMLCAaieBigEhb3LvBiQrj9FhgwjLadsj7jkgKRX/7TW8VM8zBN74czcND50aEq5fB1APhM/PoPDXvhcNu09aDTMNW0ZC3Wm9manbOkbVQV+RGnvTuOtrSGcfS36TR7nPq9c4dsXDFB3ipa6xrjRZLJHZ2xwpCWc/ZCQHYRRtcWYKcrBgZfewIqUerVu9yWq2hJ1+tw7GWW4K3DG/vjQ36q2rEkIPDh0OzkajffEP4+lQhFEovEPC1Tsmu/6yaJUvAuyelK34aM9VarWbr0OTZQ67PXsWgKQbTUquGU8/Np/p0FLcPdq/4ecQHoVQeJfwba8JPVqvfA5UapUtdNV6mbVGbYBwEuVy6YsGIkJmCmpKX1LlKYJ1eecvVQgzAtj27pPpm8q5HnIeoUoBESfiv2NRw87tun/V1tvL5wSL2sXyWC4vHws070LKF4+NSfjTEFYkZDDoP+unzc7wwdPhC2wJM++GBkhUJHBiedmtPJniyY1x0Nu8s/oNvHrOiOxAyd34wCwrcbBMybAL4iXFyAja5IjzxOK1Gdxa2drokznRPNPcKxaUk0M/jffEiG+Z4vVqta4C8LCWR703LMu6mqC7NzNPMS4fyRZtlDaK5P7HRN+d6o1XBmigZkpHw38DaB59ilKsGiAJHY=
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
