apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-dev
type: Opaque
stringData:
  database-url: "mysql://root:dev-root-password@mariadb-dev.mariadb-dev.svc.cluster.local:3306/TodoDB"
