---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    database-url: AgASB/VD23jcMNwYG53suOU1+4pOWeGTNhG4dT2faQNcJpLycXMwrSc4qfeHklVKD46H2uETkS07kamcvWMMvwPeAflGPZWHfvgxxMchCAmhlH+YvQ+7VKIDHFIhq/adf1Mf4eEDtBDPDUgWmjYMRVAJgrVwkvNyT/jyOCW05g2Fvg0H8CJigPDvJ1BnB3X9rt4O8AkMXtBAje5JTAALPEtEnzNxbztWr7gVwspnUqx3aAXWh/7L5KXOa7O22dPPa3pMI52dCZR0CqAe48lIDSFhJpr/n59dDna6EeBocJ+AGqov6RGzdZ1gonsSGp+LkfjFpbBAiLMY+WTOj5T6BIVJVOlo4SdqhMNgOyKwtxcBNcKK9kZO9C680sRn1e7cTqyOrRge9/vN0F73+Tt0Pdyby/KziEnVe+UhBmWCGF/rZdWeZChqmztPokjhNmFEIlA1Kja0X6gnb1q4+HtHRBK5Z9wDUKnV1f/+sXc1k8VuQk+19DASq8hmwy3a0fvjNO50yr1QTaNzHOm04y+Cgfeh9HwE47pwa0yyLgP4RivW1OORpfZPdwGHiTepEj6+ZoW+kiJ6QyT/fAyt0U+qNxXNE2fSavdKc3QbX7WUVGNLKG2z6OOAVl83P8NzAbieF/VMvaI47zCGsWPynXZhht+RXWYVlbX1ZGay5mhYyUDxb5xx9HoV/8avkk9tnQGCMm6OpmT60LQheTMDhZQhapHY8ewCRLLEi9JyetQKkVk1cv6yPD0WYlBc80vvu+EFtn4T1BcRQX9FVcdOBD8PHIcNAeKmmBt9sdgvz0vq4x8V2cADld/5txKBJQdN8NfmUjY=
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
