---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    database-url: AgBROlCRc9oDqd35FnZ9CXGIA3DU2DwW24U5VdL1yRBH1+7tYwT0j23eFeEkN9SAzlTyC9rE5Lb0nPYfiNNEnSamlzDhIcH+oXXW2sKgR+lSCYnbED8Q7zEJRQSOGTlxq3PtsCSTA8ZiZ9I4B01ZvrPHb6GLRN6M7s47w3yGtV5ZLiubis5tzzFqtae7bpq/fG+cnPoBEgklcfSjwLqY0zuQnqELsUL+Udv8Rc3Zq5HJ2dUkN3FPGHQROsp/gD1NWi5Er+8RpJKzDKdVI9hdUoXbYm+Ih4TZGNJ61e1SB1MeOhabyxGIzYFH5T0PNTn+rEOXqCwWfU8QSRrt5vHS+48b7bmhPId0OTmVJh13lToYKDakNRGVpfsIuUBdnt8HLQ+qDFaajiF6LPvNaDfmdPtWTgavLnpYGZMO5oT6/GTS0WoRomD9kELgEH8EE0PwLtGhg4NhZNnCm8c3pXTdafrfFVH+eDPn9LQQbIzbMldCjFGsKVW2qtPFshjqBbiALwUENC1QbqbRbFsFJ7L+xiieWf2giPIGkiTDuGaHPC9CiRVAOI72FvUvyaFJRZyEe+jo2oMlCn3IJhZwF94ALuLSmLY5m8A1BZHJKt72QICGdSbYOk8rA4EQEeDOWOoc07vlScZqppCf5oIvzkgxjzS+hVTb3hDBebUC94hred8qZJG3VN10T60mt6wOWthIqEUC57+3EPso0OP0K3xjTPY+9j9fKl/vahLjHsuJOR2+jim83gd9isnPltVdQ/G2u6EGtjVHv3vbhjhcefmGZv2jcVqpc6IpyFny/NjDyPzURykfxjEddd5ELMvd2neep18=
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
