apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-dev-secret
  namespace: todo-dev
spec:
  encryptedData:
    DATABASE_URL: AgAE0E/L99nEDdLd/th1xuGzXinmzs8MjbU+I5WtCklvitpy35sEQmWvR0wPbwkb3PA45DoJf5pxPq3ZXexa4+diMNv8V4LzgK6UAykBkHcl3fpEOR/AZJKNpjQCZ4cIg0kuZUpfdnrK7I9XGc+dnJLUEtCuvBhUX30oGIpNR3A8YG4vU5XYrhl8QHBIe3n2gniVEte9TgUGO7V8RDP7nEu5FMZluzHntfWZ6j/nMhBVj6YD7UpYXH9qdFZ+5cvYieKnu8dAn9WFwUKu8FuDVZnXavjrod2fzM8FbwgBEzyuiNq5GWQ7qG7Kf0KPTFnWtlLbVRG7BlCBVHWSxEfWoN+AUBorpAqk+iwusyscAOkl/N1iB+skPgjjjsC48fDI7VzNQU9IsN+I38yyoyL74X0Tg53iuVH2y+B3PMPbWdi7eQ8E187LWHOVW880b54pNn70SJu/aS2Kf9KwAnIZO05HC7FM1+8pDOVPmFlMfjWW6H8uUXecCbpfCU3MNGHOYkAU0TzObJVhbkhVZKEnFe8Bv7VsU9n41EK2xSOkzDPWzVLEbvZU8AZDFlB0KnTseZb+2ingRBfITFigonD+o7VDXx8rLP18LsbhX9KEf8XWz8NVfEQDBbc9argC2CaVMKls9RZo2QCOb4x0PTGKpTLDvui56W09h40qPUop0q7xJWjXBgqg90s/9W/xhbbRtew8RusG8908wx10kkAXoZaVL2/uYWEjqae7MjLsJl5HCpMSEEuFI4IoBhjMGtpfG/oM/PQYnhZnFbDtfBNbYB/1Uvei1V7m7xqzhU7dApuA/nGUmdQ=
  template:
    metadata:
      creationTimestamp: null
      name: todo-dev-secret
      namespace: todo-dev
---