apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    database-url: AgA/Kf/NRo8kih6o2xFpGMYaiBJgkcLHIRW9bEHbpd/qTlr99/A0IyacHIvO0GcoYC36DLo1VaPgFH4d/hmShJOAIXVHDrgPbWtbjNSgs0N7cdqZniXMpXs7CR9w3XTWT/7LOnDgWKYmy2Zf1MWTvLbk+ifM6nsZuLKj+Z63uSdwFW6katZUH+x+j9uBspj/C3XDPI/+Aw9SEdLFcMJ7lhq+VxBlD/ORk+hKp8OP5woZDttloUko42U06AhwQB25CZTpiQPuCTEpbVFXWEiLB2xM90gW28jHjenFo962hGfGkbcCfxB6nANOub8VDiU0sfsnSEuuVU71bSb7UDZiuvIBiTdpf6DudlaqnvXhGsKiHLP4KVo00sUrzEEfiJ4kuZsdcoks7li+H4kOvZOM4c5/KbEVwvTIVrIoNVHnjOy7ZPaqpWZxDnGcHd5ZhuxUrbe0yjSXrnFqZp9kydwgsntaDqWJ4cruRCEuEAyyGLswjBG93Ik8w7smlW7gjFZFIcSwZvdjvS9p1rXnR/w8NTFp05H+dOrxwQukquXuM1GfI2/7FZXyFsAa5407h3/fcfhTgWXtnxeZOi2h5mhjV+3kdu18nAvJtN8M8NYyZU0/FcHVSUBEpp56PcfekE9B4/SLHMVHaaAoKanbJBRuryM1l0vTxFxxxVBoo4mgscESbf/EKUATM4gteXY9gr0OkeSibFlzceWIc8G9PuCtMkK7m8pgyGFy3gSJA7/D6Dfcxx60CiB60F40/0nBMrX07xJudFkt9EPZLA8dz0LqBn2DIa5Ho7iS0LX/A4SBhfFTqcPHZj0=
  template:
    metadata:
      creationTimestamp: null
      name: todo-secrets
      namespace: todo-dev
