---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
    database-url: AgAPEvsU1qOzsGhJUREl2NuovcVTMqcFs8gsKzX2troITNRZxBjQqQH8IOG4xuS61JaKA+5mLEueNcWZNiOPF6QY1Qyz10P51vsBwf/lhTAhkS/Hmobn+bsKUaq6D0wH4rKOsflyFYkuJYDoN0LX5WJ6LEC9n7NRbc3O21qsH13tTFT3ZL64FrotVGf6Ef6kOHcXir4RKATCxS9P2a7lpEpU2m5DvPeQVxhL3bEArFXugZDQSngoLE+SG9l+VIrZitKU6X7/UGIj+LM1LwRhBhd9QKmtPb7iaZZsOQ2wlOsL9NsjL9ZkYDVPKH/KbWMR3239OuijvbEectJWuKh60n2T+FjC+KmprFGK7BgDpy8la0sH4YuDG0nydBf/os0a06/Eew8x/mBHVeiHSzLHRItCpeKaa6zpDUqwabi5rA6QlC/E0rtUoKYJtruXja5lbHJVV3gSL2ddvcONvcF1P5fzpfdNOfn4AO5vjW9O9pod5AEGqenoQje7FPZspgS9y3S7iFAJBj/aOmsRP+lQgCb0C/LqhAWKVgRckHdKvSwBaIm/eTSZn9DeKAmz4+w2/guRepwQM/0IUc+UnaG+jpK1LSBvpurSophyOz2K5mSVFtJ+FrBnwcH4DPlvSlUUz7UQr5CKlcY/UmVvxoNerZ7U22TMlPx54AJaWH4wxl6KpscokY6Yjg16RfhR18J3J1sBnGyLSh27PAmvT2jsri59TwGmcHUm1mfP0gRNmvqXl3cmljmWr5ji3lbBTDWXltzsHKjMht70PLgQNILwnFYj+eVJGQd4PglBHRNOl0T1vBJRnQ==
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
    type: Opaque
