---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-secrets
  namespace: todo-dev
spec:
  encryptedData:
<<<<<<< HEAD
    database-url: AgASB/VD23jcMNwYG53suOU1+4pOWeGTNhG4dT2faQNcJpLycXMwrSc4qfeHklVKD46H2uETkS07kamcvWMMvwPeAflGPZWHfvgxxMchCAmhlH+YvQ+7VKIDHFIhq/adf1Mf4eEDtBDPDUgWmjYMRVAJgrVwkvNyT/jyOCW05g2Fvg0H8CJigPDvJ1BnB3X9rt4O8AkMXtBAje5JTAALPEtEnzNxbztWr7gVwspnUqx3aAXWh/7L5KXOa7O22dPPa3pMI52dCZR0CqAe48lIDSFhJpr/n59dDna6EeBocJ+AGqov6RGzdZ1gonsSGp+LkfjFpbBAiLMY+WTOj5T6BIVJVOlo4SdqhMNgOyKwtxcBNcKK9kZO9C680sRn1e7cTqyOrRge9/vN0F73+Tt0Pdyby/KziEnVe+UhBmWCGF/rZdWeZChqmztPokjhNmFEIlA1Kja0X6gnb1q4+HtHRBK5Z9wDUKnV1f/+sXc1k8VuQk+19DASq8hmwy3a0fvjNO50yr1QTaNzHOm04y+Cgfeh9HwE47pwa0yyLgP4RivW1OORpfZPdwGHiTepEj6+ZoW+kiJ6QyT/fAyt0U+qNxXNE2fSavdKc3QbX7WUVGNLKG2z6OOAVl83P8NzAbieF/VMvaI47zCGsWPynXZhht+RXWYVlbX1ZGay5mhYyUDxb5xx9HoV/8avkk9tnQGCMm6OpmT60LQheTMDhZQhapHY8ewCRLLEi9JyetQKkVk1cv6yPD0WYlBc80vvu+EFtn4T1BcRQX9FVcdOBD8PHIcNAeKmmBt9sdgvz0vq4x8V2cADld/5txKBJQdN8NfmUjY=
=======
    database-url: AgBROlCRc9oDqd35FnZ9CXGIA3DU2DwW24U5VdL1yRBH1+7tYwT0j23eFeEkN9SAzlTyC9rE5Lb0nPYfiNNEnSamlzDhIcH+oXXW2sKgR+lSCYnbED8Q7zEJRQSOGTlxq3PtsCSTA8ZiZ9I4B01ZvrPHb6GLRN6M7s47w3yGtV5ZLiubis5tzzFqtae7bpq/fG+cnPoBEgklcfSjwLqY0zuQnqELsUL+Udv8Rc3Zq5HJ2dUkN3FPGHQROsp/gD1NWi5Er+8RpJKzDKdVI9hdUoXbYm+Ih4TZGNJ61e1SB1MeOhabyxGIzYFH5T0PNTn+rEOXqCwWfU8QSRrt5vHS+48b7bmhPId0OTmVJh13lToYKDakNRGVpfsIuUBdnt8HLQ+qDFaajiF6LPvNaDfmdPtWTgavLnpYGZMO5oT6/GTS0WoRomD9kELgEH8EE0PwLtGhg4NhZNnCm8c3pXTdafrfFVH+eDPn9LQQbIzbMldCjFGsKVW2qtPFshjqBbiALwUENC1QbqbRbFsFJ7L+xiieWf2giPIGkiTDuGaHPC9CiRVAOI72FvUvyaFJRZyEe+jo2oMlCn3IJhZwF94ALuLSmLY5m8A1BZHJKt72QICGdSbYOk8rA4EQEeDOWOoc07vlScZqppCf5oIvzkgxjzS+hVTb3hDBebUC94hred8qZJG3VN10T60mt6wOWthIqEUC57+3EPso0OP0K3xjTPY+9j9fKl/vahLjHsuJOR2+jim83gd9isnPltVdQ/G2u6EGtjVHv3vbhjhcefmGZv2jcVqpc6IpyFny/NjDyPzURykfxjEddd5ELMvd2neep18=
>>>>>>> develop
  template:
    metadata:
      name: todo-secrets
      namespace: todo-dev
